version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building project..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying project..."

artifacts:
  files:
    - '**/*'

env:
  variables:
    - NODE_ENV: "production"
    - DB_HOST: "football-dev-db.cluster-cewxamjmap5r.us-east-2.rds.amazonaws.com"
    - DB_PORT: 3306
    - DB_USER: "futtestolyio"
    - DB_PASSWORD: "macandreRodrigues10A"
    - DB_DATABASE: "football_data"

computeType: BUILD_GENERAL1_SMALL
