version: '3'
services:
  app:
    build: .
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=dev
      - PORT=8081
      - secret=supersecretkey
      - SENDGRID_API_KEY=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
      - NODE_MAILER_PASSWORD=q56NTjwTVgi9
      - FRONT_END_URL=http://localhost:3000
    command: ["node", "./bin/www"]
