version: '3'
services:
  app:
    build: .
    ports:
      - '8081:8081'
    environment:
      - NODE_ENV=dev
      - DB_HOST=SG-bird-handle-7872-7413-mysql-master.servers.mongodirector.com
      - DB_USER=sgroot
      - DB_PASSWORD=kTEnc6v-MyY81OFb
      - DB_NAME=footballdata
      - PORT=8081
      - secret=supersecretkey
      - DISCORD_CLIENT_ID=1076096752660258836
      - DISCORD_CLIENT_SECRET=0VDEMNwogfgf-lhl6m2A552C9A7QtAGM
      - SENDGRID_API_KEY=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
    command: ["node", "./bin/www"]
