version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: footballdata
      MYSQL_USER: futtestolyio
      MYSQL_PASSWORD: futtestolyiosoccer2020A@
      MYSQL_ROOT_PASSWORD: futtestolyiosoccer2020A@
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./footballdata.sql:/docker-entrypoint-initdb.d/database.sql
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db-data:
